Models/ErrorViewModel.cs
using System;

namespace hera.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/CompetitorsDatabaseController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using hera.Models;

namespace hera.Controllers
{
    public class CompetitorsDatabaseController : Controller
    {
        private readonly ILogger<CompetitorsDatabaseController> _logger;

        public CompetitorsDatabaseController(ILogger<CompetitorsDatabaseController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/ComplianceDatabaseController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using hera.Models;

namespace hera.Controllers
{
    public class ComplianceDatabaseController : Controller
    {
        private readonly ILogger<ComplianceDatabaseController> _logger;

        public ComplianceDatabaseController(ILogger<ComplianceDatabaseController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using hera.Models;

namespace hera.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/IngredientsDatabaseController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using hera.Models;

namespace hera.Controllers
{
    public class IngredientsDatabaseController : Controller
    {
        private readonly ILogger<IngredientsDatabaseController> _logger;

        public IngredientsDatabaseController(ILogger<IngredientsDatabaseController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/ProductDatabaseController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using hera.Models;

namespace hera.Controllers
{
    public class ProductDatabaseController : Controller
    {
        private readonly ILogger<ProductDatabaseController> _logger;

        public ProductDatabaseController(ILogger<ProductDatabaseController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/RecipeDatabaseController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using hera.Models;

namespace hera.Controllers
{
    public class RecipeDatabaseController : Controller
    {
        private readonly ILogger<RecipeDatabaseController> _logger;

        public RecipeDatabaseController(ILogger<RecipeDatabaseController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/RecipeIngredientsDatabaseController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using hera.Models;

namespace hera.Controllers
{
    public class RecipeIngredientsDatabaseController : Controller
    {
        private readonly ILogger<RecipeIngredientsDatabaseController> _logger;

        public RecipeIngredientsDatabaseController(ILogger<RecipeIngredientsDatabaseController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Shared/_Layout.cshtml
<!--
=========================================================
* * Black Dashboard - v1.0.1
=========================================================

* Product Page: https://www.creative-tim.com/product/black-dashboard
* Copyright 2019 Creative Tim (https://www.creative-tim.com)


* Coded by Creative Tim

=========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
-->
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link rel="apple-touch-icon" sizes="76x76" href="~/lib/assets/img/apple-icon.png">
	<link rel="icon" type="image/png" href="~/lib/assets/img/favicon.png">
	<title>@ViewData["Title"] - dashboard admin</title>
	<!--     Fonts and icons     -->
	<link href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,600,700,800" rel="stylesheet" />
	<link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
	<!-- Nucleo Icons -->
	<link href="~/lib/assets/css/nucleo-icons.css" rel="stylesheet" />
	<!-- CSS Files -->
	<link href="~/lib/assets/css/black-dashboard.css?v=1.0.0" rel="stylesheet" />
	<!-- CSS Just for demo purpose, don't include it in your project -->
	<link href="~/lib/assets/demo/demo.css" rel="stylesheet" />
</head>

<body class="">
	<div class="wrapper">
		<div class="sidebar">
			<!--
        Tip 1: You can change the color of the sidebar using: data-color="blue | green | orange | red"
    -->
			<div class="sidebar-wrapper">
				<div class="logo">
					<a href="javascript:void(0)" class="simple-text logo-mini">
						NDP
					</a>
					<a href="javascript:void(0)" class="simple-text logo-normal">
						MENU DATABASE
					</a>
				</div>
				<ul class="nav">
					<li class="active ">
						<a asp-area="" asp-controller="Home" asp-action="Index">
							<i class="tim-icons icon-chart-pie-36"></i>
							<p>Dashboard</p>
						</a>
					</li>
					<li>
						<a asp-area="" asp-controller="CompetitorsDatabase" asp-action="Index">
							<i class="tim-icons icon-atom"></i>
							<p>Competitors Database</p>
						</a>
					</li>
					<li>
						<a asp-area="" asp-controller="ProductDatabase" asp-action="Index">
							<i class="tim-icons icon-pin"></i>
							<p>Product Database</p>
						</a>
					</li>
					<li>
						<a asp-area="" asp-controller="RecipeDatabase" asp-action="Index">
							<i class="tim-icons icon-bell-55"></i>
							<p>Recipe Database</p>
						</a>
					</li>
					<li>
						<a asp-area="" asp-controller="ComplianceDatabase" asp-action="Index">
							<i class="tim-icons icon-single-02"></i>
							<p>Compliance Database</p>
						</a>
					</li>
					<li>
						<a asp-area="" asp-controller="IngredientsDatabase" asp-action="Index">
							<i class="tim-icons icon-align-center"></i>
							<p>Ingredients Database </p>
						</a>
					</li>
					<li>
						<a asp-area="" asp-controller="RecipeIngredientsDatabase" asp-action="Index">
							<i class="tim-icons icon-world"></i>
							<p>Recipe Ingredients Database</p>
						</a>
					</li>
					<li>
						<a asp-area="" asp-controller="IngredientsComparisonDatabase" asp-action="Index">
							<i class="tim-icons icon-spaceship"></i>
							<p>Ingredients Comparison </p>
						</a>
					</li>
					<li>
						<a asp-area="" asp-controller="ProductDesignMatrixDatabase" asp-action="Index">
							<i class="tim-icons icon-bank"></i>
							<p>Product Design Matrix </p>
						</a>
					</li>
				</ul>
			</div>
		</div>
		<div class="main-panel">
			<!-- Navbar -->
			<nav class="navbar navbar-expand-lg navbar-absolute navbar-transparent">
				<div class="container-fluid">
					<div class="navbar-wrapper">
						<div class="navbar-toggle d-inline">
							<button type="button" class="navbar-toggler">
								<span class="navbar-toggler-bar bar1"></span>
								<span class="navbar-toggler-bar bar2"></span>
								<span class="navbar-toggler-bar bar3"></span>
							</button>
						</div>
						<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DASHBOARD NDP FONTERRA</a>
					</div>
					<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation"
						aria-expanded="false" aria-label="Toggle navigation">
						<span class="navbar-toggler-bar navbar-kebab"></span>
						<span class="navbar-toggler-bar navbar-kebab"></span>
						<span class="navbar-toggler-bar navbar-kebab"></span>
					</button>
					<div class="collapse navbar-collapse" id="navigation">
						<ul class="navbar-nav ml-auto">
							<li class="search-bar input-group">
								<button class="btn btn-link" id="search-button" data-toggle="modal" data-target="#searchModal"><i
										class="tim-icons icon-zoom-split"></i>
									<span class="d-lg-none d-md-block">Search</span>
								</button>
							</li>
							<li class="dropdown nav-item">
								<a href="javascript:void(0)" class="dropdown-toggle nav-link" data-toggle="dropdown">
									<div class="notification d-none d-lg-block d-xl-block"></div>
									<i class="tim-icons icon-sound-wave"></i>
									<p class="d-lg-none">
										Notifications
									</p>
								</a>
								<ul class="dropdown-menu dropdown-menu-right dropdown-navbar">
									<li class="nav-link"><a href="#" class="nav-item dropdown-item">Mike John responded to your email</a>
									</li>
									<li class="nav-link"><a href="javascript:void(0)" class="nav-item dropdown-item">You have 5 more
											tasks</a></li>
									<li class="nav-link"><a href="javascript:void(0)" class="nav-item dropdown-item">Your friend Michael
											is in town</a></li>
									<li class="nav-link"><a href="javascript:void(0)" class="nav-item dropdown-item">Another
											notification</a></li>
									<li class="nav-link"><a href="javascript:void(0)" class="nav-item dropdown-item">Another one</a></li>
								</ul>
							</li>
							<li class="dropdown nav-item">
								<a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
									<div class="photo">
										<img src="~/lib/assets/img/anime3.png" alt="Profile Photo">
									</div>
									<b class="caret d-none d-lg-block d-xl-block"></b>
									<p class="d-lg-none">
										Log out
									</p>
								</a>
								<ul class="dropdown-menu dropdown-navbar">
									<li class="nav-link"><a href="javascript:void(0)" class="nav-item dropdown-item">Profile</a></li>
									<li class="nav-link"><a href="javascript:void(0)" class="nav-item dropdown-item">Settings</a></li>
									<li class="dropdown-divider"></li>
									<li class="nav-link"><a asp-area="" asp-page="/Login" class="nav-item dropdown-item">Log out</a></li>
								</ul>
							</li>
							<li class="separator d-lg-none"></li>
						</ul>
					</div>
				</div>
			</nav>
			<div class="modal modal-search fade" id="searchModal" tabindex="-1" role="dialog" aria-labelledby="searchModal"
				aria-hidden="true">
				<div class="modal-dialog" role="document">
					<div class="modal-content">
						<div class="modal-header">
							<input type="text" class="form-control" id="inlineFormInputGroup" placeholder="SEARCH">
							<button type="button" class="close" data-dismiss="modal" aria-label="Close">
								<i class="tim-icons icon-simple-remove"></i>
							</button>
						</div>
					</div>
				</div>
			</div>
			<!-- End Navbar -->

			@* Start Main Content *@
				@RenderBody()
			@* End Main Content *@

			@* Start Footer *@
			<footer class="footer">
				<div class="container-fluid">
					<ul class="nav">
						<li class="nav-item">
							<a href="javascript:void(0)" class="nav-link">
								About Us
							</a>
						</li>
					</ul>
					<div class="copyright">
						©
						<script>
							document.write(new Date().getFullYear())
						</script> made with <i class="tim-icons icon-heart-2"></i> by
						<a href="https://www.fonterra.com/" target="_blank">Fonterra </a>Co-operative Group.
					</div>
				</div>
			</footer>
			@* End Footer *@

		</div>
	</div>
	<!--   Core JS Files   -->
	<script src="~/lib/assets/js/core/jquery.min.js"></script>
	<script src="~/lib/assets/js/core/popper.min.js"></script>
	<script src="~/lib/assets/js/core/bootstrap.min.js"></script>
	<script src="~/lib/assets/js/plugins/perfect-scrollbar.jquery.min.js"></script>
	<!--  Google Maps Plugin    -->
	<!-- Place this tag in your head or just before your close body tag. -->
	<script src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>
	<!-- Chart JS -->
	<script src="~/lib/assets/js/plugins/chartjs.min.js"></script>
	<!--  Notifications Plugin    -->
	<script src="~/lib/assets/js/plugins/bootstrap-notify.js"></script>
	<!-- Control Center for Black Dashboard: parallax effects, scripts for the example pages etc -->
	<script src="~/lib/assets/js/black-dashboard.min.js?v=1.0.0"></script>
	<!-- Black Dashboard DEMO methods, don't include it in your project! -->
	<script src="~/lib/assets/demo/demo.js"></script>
	<script>
		$(document).ready(function () {
			$().ready(function () {
				$sidebar = $('.sidebar');
				$navbar = $('.navbar');
				$main_panel = $('.main-panel');

				$full_page = $('.full-page');

				$sidebar_responsive = $('body > .navbar-collapse');
				sidebar_mini_active = true;
				white_color = false;

				window_width = $(window).width();

				fixed_plugin_open = $('.sidebar .sidebar-wrapper .nav li.active a p').html();



				$('.fixed-plugin a').click(function (event) {
					if ($(this).hasClass('switch-trigger')) {
						if (event.stopPropagation) {
							event.stopPropagation();
						} else if (window.event) {
							window.event.cancelBubble = true;
						}
					}
				});

				$('.fixed-plugin .background-color span').click(function () {
					$(this).siblings().removeClass('active');
					$(this).addClass('active');

					var new_color = $(this).data('color');

					if ($sidebar.length != 0) {
						$sidebar.attr('data', new_color);
					}

					if ($main_panel.length != 0) {
						$main_panel.attr('data', new_color);
					}

					if ($full_page.length != 0) {
						$full_page.attr('filter-color', new_color);
					}

					if ($sidebar_responsive.length != 0) {
						$sidebar_responsive.attr('data', new_color);
					}
				});

				$('.switch-sidebar-mini input').on("switchChange.bootstrapSwitch", function () {
					var $btn = $(this);

					if (sidebar_mini_active == true) {
						$('body').removeClass('sidebar-mini');
						sidebar_mini_active = false;
						blackDashboard.showSidebarMessage('Sidebar mini deactivated...');
					} else {
						$('body').addClass('sidebar-mini');
						sidebar_mini_active = true;
						blackDashboard.showSidebarMessage('Sidebar mini activated...');
					}

					// we simulate the window Resize so the charts will get updated in realtime.
					var simulateWindowResize = setInterval(function () {
						window.dispatchEvent(new Event('resize'));
					}, 180);

					// we stop the simulation of Window Resize after the animations are completed
					setTimeout(function () {
						clearInterval(simulateWindowResize);
					}, 1000);
				});

				$('.switch-change-color input').on("switchChange.bootstrapSwitch", function () {
					var $btn = $(this);

					if (white_color == true) {

						$('body').addClass('change-background');
						setTimeout(function () {
							$('body').removeClass('change-background');
							$('body').removeClass('white-content');
						}, 900);
						white_color = false;
					} else {

						$('body').addClass('change-background');
						setTimeout(function () {
							$('body').removeClass('change-background');
							$('body').addClass('white-content');
						}, 900);

						white_color = true;
					}


				});

				$('.light-badge').click(function () {
					$('body').addClass('white-content');
				});

				$('.dark-badge').click(function () {
					$('body').removeClass('white-content');
				});
			});
		}); <
		/script> <
		script >
			$(document).ready(function () {
				// Javascript method's body can be found in assets/js/demos.js
				demo.initDashboardPageCharts();

			});
	</script>
	<script>
		$(document).ready(function () {
			// Javascript method's body can be found in assets/js/demos.js
			demo.initDashboardPageCharts();

		});
	</script>
	<script src="https://cdn.trackjs.com/agent/v3/latest/t.js"></script>
	<script>
		window.TrackJS &&
			TrackJS.install({
				token: "ee6fab19c5a04ac1a32a645abde4613a",
				application: "black-dashboard-free"
			});
	</script>
</body>

</html>